name: Ruby on Rails CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: career_crafter_pro_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.0" # Specify the Ruby version if different
      - name: Install dependencies
        run: |
          sudo apt-get install libpq-dev
          bundle install
      - name: Setup database
        run: |
          bin/rails db:create
          bin/rails db:schema:load RAILS_ENV=test
      - name: Run tests
        run: bundle exec rspec
